[package]
name = "rust_git_project"
version = "0.1.0"
authors = ["Ollie <oliverrylance@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[[bin]]
name = "rust_git_project"
path = "main.rs"